version: '3'

services:
  rating-postgres-service:
    container_name: rating-postgres
    deploy:
      replicas: 1
    image: postgres:13.4
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ratingdb
